accounts/urls.py
from django.urls import path
from .views import registration_view

urlpatterns = [
    path("registration/", registration_view, name="registration" )
]

core/urls.py
from django.urls import path
from .views import homepage, UserDetailView, UserList, search_tracking_code, LotDetailView, track_hash_page, track_hash_result
urlpatterns = [
    path("", homepage, name="homepage"),
    path("user/<int:pk>/", UserDetailView.as_view(), name="user_profile"),
    path("user_list/", UserList.as_view(), name="user_list"),
    path("search/", search_tracking_code, name="search_tracking_code"),
    path("lot_detail/<int:pk>/", LotDetailView.as_view(), name="lot_detail"),
    path("track_hash_page/", track_hash_page, name="track_hash_page"),
    path("track_hash_result/", track_hash_result, name="track_hash_result"),
]

products/urls.py
from django.urls import path
from .views import LotRegistrationCreateView

urlpatterns = [
    path("registration/", LotRegistrationCreateView.as_view(), name="lot_registration"),
]

vegan_style/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls')),
    path('products/', include('products.urls')),
    path('accounts/', include('accounts.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)

accounts/models.py
from django.db import models

# Create your models here.

core/models.py
from django.db import models

# Create your models here.

products/models.py
from django.urls import reverse
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User
from .utils import generic_info_dict, send_transaction
import hashlib

class Lot(models.Model):
    lot_code = models.CharField(max_length=20)
    tracking_code = models.CharField(max_length=10)
    product = models.CharField(max_length=30)
    production_quantity = models.CharField(max_length=10)
    date_time_arrival = models.DateTimeField(default=timezone.now)
    date_time_production =models.DateTimeField(default=timezone.now)
    manufacturing_plant = models.CharField(max_length=30)
    recipient = models.CharField(max_length=20)
    created_by = models.ForeignKey(User, on_delete=models.CASCADE, editable=False, null=True)
    hash = models.CharField(max_length=64, blank=True, null=True)
    hash_lot = models.CharField(max_length=64, blank=True, null=True)
    hash_info = models.CharField(max_length=64, blank=True, null=True)
    tx_id = models.CharField(max_length=100, blank=True, null=True) 

    def __str__(self):
        return self.lot_code

    class Meta:
        verbose_name = "Lot"
        verbose_name_plural = "Lot"
        ordering = ['-date_time_production']

    def get_absolute_url(self):
        return reverse("lot_detail", kwargs={'pk':self.pk})

    def save(self):
        info = str(generic_info_dict(self))
        self.hash_lot = hashlib.sha256(self.lot_code.encode('utf-8')).hexdigest()
        self.hash_info = hashlib.sha256(info.encode('utf-8')).hexdigest()
        self.hash = self.hash_lot + "    " + self.hash_info
        self.tx_id = self.write_on_chain()
        super(Lot, self).save()

    def write_on_chain(self):
        return send_transaction(self.hash)
        

accounts/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User

class RegistrationForm(UserCreationForm):
    email = forms.EmailField(max_length=30, required=True) #email is not present in UserCreateForm
    
    class Meta:
        model = User
        fields = ["username", "password1", "password2", "email"]
        

core/forms.py
from django import forms
from products.models import Lot

class HashLotModelForm(forms.ModelForm):

    class Meta:
        model = Lot
        fields = ['hash']

accounts/views.py
from django.shortcuts import render
from .forms import RegistrationForm
from django.shortcuts import HttpResponseRedirect
from django.contrib.auth import login, authenticate
from django.contrib.auth.models import User

def registration_view(request):
    if request.method == "POST":
        form = RegistrationForm(request.POST)
        if form.is_valid():
            username = form.cleaned_data['username']
            email = form.cleaned_data['email']
            password = form.cleaned_data['password1']
            User.objects.create_user(username=username, password=password, email=email)
            user = authenticate(username=username, password=password)
            login(request, user)
            return HttpResponseRedirect("/")
    else:
        form = RegistrationForm()
    context = {'form':form}
    return render(request, 'accounts/registration.html', context)
    

core/views.py
from django.shortcuts import render
from products.models import Lot
from django.contrib.auth.models import User
from .forms import HashLotModelForm
from django.views.generic import ListView, DetailView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.admin.views.decorators import staff_member_required
from django.utils.decorators import method_decorator
from django.http import HttpResponse
import redis

client = redis.StrictRedis(host='127.0.0.1', port='6379', password="", db=0)

def homepage(request):
    return render(request, "core/homepage.html")

class UserDetailView(DetailView):
    model = User
    context_object_name = 'user'
    template_name = 'core/user_profile.html'

@method_decorator(staff_member_required, name='dispatch')
class UserList(ListView):
    model = User
    context_object_name = 'users'
    template_name = 'core/user_list.html'

def search_tracking_code(request):
    if request.method == "POST":
        searched =request.POST['searched']
        lots = Lot.objects.filter(tracking_code__contains=searched)
        return render(request, 'core/search_tracking_code.html', {"searched": searched, "lots": lots})
    else:
        return render(request, 'core/search_tracking_code.html')

class LotDetailView(LoginRequiredMixin, DetailView):
    template_name = "core/lot_detail.html"
    model = Lot

def track_hash_page(request):
    form = HashLotModelForm
    context = {"form":form}
    return render(request, "core/track_hash_page.html", context)

def track_hash_result(request):
    if request.method == "POST":
        q =request.POST['q']
        hashes = Lot.objects.filter(hash__contains=q)
        return render(request, 'core/track_hash_result.html', {"q": q, "hashes": hashes})
    else:
        return render(request, 'core/track_hash_result.html')

def check_last_ip(request):
    username = request.user.username
    last_ip = client.get(username)
    current_ip = request.META['REMOTE_ADDR']
    if last_ip is None:
        client.set(username, current_ip)
    elif current_ip != last_ip:
        client.set(username, current_ip)
        return HttpResponse("current ip address is different from the previous one")

products/views.py
from django.views.generic import CreateView
from django.contrib.auth.mixins import LoginRequiredMixin
from .models import Lot

class LotRegistrationCreateView(LoginRequiredMixin, CreateView):
    model = Lot
    fields = ["lot_code", "tracking_code", "product", "production_quantity", "date_time_arrival", "date_time_production", "manufacturing_plant", "recipient"]
    template_name = "products/lot_registration.html"
    success_url = "/"

    def form_valid(self, form):
        form.instance.created_by = self.request.user
        return super().form_valid(form)

accounts/templates/accounts/registration.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block head_title %}{{ block.super }} - Sign Up{% endblock head_title %}
{% block content %}
    <div class="row justify-content-center">
        <div class="col-6 text-center">
            <h3 class="mt-4 mb-5">Sign up Here:</h3>
            <div class="container-lg">
                <form method="POST" novalidate>
                    {% csrf_token %}
                    {{ form|crispy }}
                    <input type="submit" class="btn my-2" style="background-color: #90EE90;" value="Sign up" >
                </form>
            </div>
        </div>  
    </div>
{% endblock content %}

core/templates/core/homepage.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block head_title %}{{ block.super }} - Homepage{% endblock head_title %}
{% block content %}
    <div class="container text-center mt-5">
        <h1>WELCOME!</h1>
        <p class="mt-4">this is where food sustainability and blockchain interact for a better future</p>
    </div>
    <div class="card-group mt-5">
        <div class="card">
          <img class="card-img-top" src="https://www.my-personaltrainer.it/2020/09/07/dieta-vegana-orig.jpeg" alt="Card image cap">
          <div class="card-body">
            <h5 class="card-title text-center">SUSTAINABILITY</h5>
            <p class="card-text"></p>
          </div>
        </div>
        <div class="card">
          <img class="card-img-top" src="https://mpng.subpng.com/20180629/zah/kisspng-blockchain-business-bitcoin-technology-supply-chai-time-consuming-5b36918caeef03.6380893815303028607165.jpg" alt="Card image cap">
          <div class="card-body">
            <h5 class="card-title text-center">BLOCKCHAIN</h5>
            <p class="card-text"></p>
          </div>
        </div>
      </div>
    
{% endblock content %}

core/templates/core/lot_detail.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block head_title %}{{ block.super }} - Lot - Detail{% endblock head_title %}
{% block content %}
<div class="container">
    <div class="row mt-3">
        <div class="col-4">
            <div class="card my-2">
                <div class="card-header">
                    <h5>Tracking Code:</h5> <p>{{ object.tracking_code }}</p>
                </div>
                <div class="card-body">
                    Registered By: <p class="mt-2 mb-0"><strong>{{ object.created_by }}</strong></p>
                </div>
                <div class="card-footer"></div>
            </div>
        </div>    
        <div class="col-8">
            <div class="card my-2">
                <div class="card-header"></div>
                <div class="card-body">
                    <p class="text-center mb-1"><strong>Lot Code:</strong></p><p class="text-center">{{ object.lot_code }}</p><hr>
                    <p class="text-center mb-1"><strong>Product:</strong></p><p class="text-center">{{ object.product }}</p><hr>
                    <p class="text-center mb-1"><strong>Production Quantity:</strong></p><p class="text-center">{{ object.production_quantity }}</p><hr>
                    <p class="text-center mb-1"><strong>Date&Time Arrival:</strong></p><p class="text-center">{{ object.date_time_arrival }}</p><hr>
                    <p class="text-center mb-1"><strong>Date&Time Production:</strong></p><p class="text-center">{{ object.date_time_production }}</p><hr>
                    <p class="text-center mb-1"><strong>Manufacturing Plant:</strong></p><p class="text-center">{{ object.manufacturing_plant}}</p><hr>
                    <p class="text-center mb-1"><strong>Recipient:</strong></p><p class="text-center mb-1">{{ object.recipient }}</p>
                </div>
                <div class="card-footer"></div>
            </div>
        </div>        
    </div>
</div>
{% endblock content %}

core/templates/core/search_tracking_code.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block head_title %}{{ block.super }} - Search for tracking Code{% endblock head_title %}
{% block content %}
<div class="row justify-content-center mt-4">
    
    <div class="col-3 text-center">
        {% csrf_token %}
        {% if searched %}
            <p class="text-center my-4">You Searched For... "{{ searched }}"</p>
            {% for lot in lots %}
                <a href="{{ lot.get_absolute_url }}">{{ lot.tracking_code }}</a><br><hr>
            {% endfor %}
        {% else %}
            <p class="text-center mt-4">---</p>
        {% endif %}  
    </div>
</div>
{% endblock content %}

core/templates/core/track_hash_page.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block head_title %}{{ block.super }} - Track Lot - Page{% endblock head_title %}
{% block content %}
{% csrf_token %}
<div class="row justify-content-center">
    <div class="col-6 text-center">
        <div class="card my-5">
            <div class="card-header"></div>
            <div class="container mb-5">
                <h5 class="my-5">Track Lot in the Blockchain</h5>
                <form class="d-flex mx-2" method="POST" action="{% url 'track_hash_result' %}">
                    {% csrf_token %}
                    <input name="q" class="form-control me-2" type="q" placeholder=" Lot Hash" aria-label="q">
                    <input type="submit" class="btn mx-2" style="background-color: #90EE90;" value="Track Lot" >
                </form>
            </div>
            <div class="card-footer"></div>
        </div>
        
    </div>  
</div>
{% endblock content %}

            <!-- <form name="q" action="{% url 'track_lot_result' %}">
                {% csrf_token %}
                {{ form|crispy }}
                <input type="submit" class="btn my-2" style="background-color: #90EE90;" value="Track Lot" >
            </form> -->

core/templates/core/track_hash_result.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block head_title %}{{ block.super }} - Track Lot - Result{% endblock head_title %}
{% block content %}
<div class="container">
    <div class="row mt-3 mx-5"> 
        <div class="col-12">
            <div class="card my-2">
                <div class="card-header"></div>
                <div class="card-body">
                    {% if q %}
                        {% for hash in hashes %}
                            <h6 class="text-center my-4"><strong>Transaction ID:</strong></h6>
                            <p class="text-center my-4">{{ hash.tx_id }}</p>
                            <p class="text-center my-4"><small> Look for it in the <a href="https://ropsten.etherscan.io/">Ropsten Ethereum Blockchain</a></small></p><hr>
                            <h6 class="text-center my-4"><strong>Generic Info:</strong></h6>
                            <li class="text-center my-4">{{ hash.lot_code }}</li>
                            <li class="text-center my-4">{{ hash.tracking_code }}</li>
                            <li class="text-center my-4">{{ hash.product }}</li>
                            <li class="text-center my-4">{{ hash.production_quantity }}</li>
                            <li class="text-center my-4">{{ hash.date_time_arrival }}</li>
                            <li class="text-center my-4">{{ hash.date_time_production }}</li>
                            <li class="text-center my-4">{{ hash.manufacturing_plant }}</li>
                            <li class="text-center my-4">{{ hash.recipient }}</li>
                            <li class="text-center mt-4">{{ hash.created_by }}</li>
                        {% endfor %}
                    {% else %}
                        <p class="text-center mt-4">---</p>
                    {% endif %}  
                </div>
                <div class="card-footer"></div>
            </div>
        </div>        
    </div>
</div>
{% endblock content %}

core/templates/core/user_list.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block head_title %}{{ block.super }} - Users - List{% endblock head_title %}
{% block content %}

<div class="container mt-5">
  {% for user in users %}
    {% if forloop.first %}<div class="row">{% endif %}
      <div class="card border-success mb-3" style="max-width: 18rem;">
        <div class="card-header"></div>
        <div class="card-body text-success">
          <p class="card-text text-center"><a href="{% url 'user_profile' pk=user.pk %}" class="link-success"><strong class="text-center">{{ user.username }}</strong></a></p>
        </div>
        <div class="card-footer"></div>
        </div>
      </dir>
      <br>
    {% if forloop.counter|divisibleby:"4" or forloop.last %}</div>{% endif %}
    {% if forloop.counter|divisibleby:"4" and not forloop.last %}<div class="row">{% endif %}
  {% endfor %}
</div>  

{% endblock content %}

core/templates/core/user_profile.html
{% extends 'base.html' %}

{% block head_title %}{{ block.super }} - {{ user }}{% endblock head_title %}
{% block content %}
    <div class="row justify-content-center mt-4">
        <div class="col-3 text-center">
            <div class="card my-2">
                <div class="card-header">
                    <h4 class="text-center text-success">{{ user }}</h4>
                </div>
                <div class="card-body">
                    <p>Lot/s Registered:    {{ user.lot_set.count }} </p>
                </div>
                <div class="card-footer"></div>
            </div>
        </div>
    </div>
    <div class="container">
        <div class="col-12">
            {% for lot in user.lot_set.all %}
              <div class="col-12 mt-3">
                <div class="card mb-4">
                  <div class="card-header py-1">
                      <p>Date and Time Production of the Lot:</p>
                      <p class="mb-0 text-muted">{{ lot.date_time_production|date:'d M Y - H:m:s' }}</p>
                  </div>
                  <div class="card-body">
                    <h5 class="text-success">Hash:</h5>{{ lot.hash }}<hr>
                    <h5 class="text-success">Tx_Id:</h5>{{ lot.tx_id }}
                  </div>
                  <div class="card-footer"></div>
                </div>
              </div>
            {% endfor %}
          </div>
        </div>
    </div>
    
{% endblock content %}

products/templates/products/lot_registration.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block head_title %}{{ block.super }} - Lot - Registration{% endblock head_title %}
{% block content %}
<div class="row justify-content-center mt-4">
    <div class="col-3 text-center">
        <p class="text-center mt-3 mb-5"><strong>Hi {{ request.user.username }}, register a new lot down below:</strong></p>
        <form action="" method="POST" novalidate>
            {% csrf_token %}
            {{ form|crispy }}
            <input type="submit" class="btn my-2" style="background-color: #90EE90;" value="Register">
        </form>
    </div>
</div>
{% endblock content %}

templates/base.html
{% load static %}
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <link rel="stylesheet" type= "text/css" href="{% static 'css/style_homepage.css' %}">
    <title>{% block head_title %}Vegan Style{% endblock head_title %}</title>
  </head>
  <body>
    <nav class="navbar navbar-expand-lg navbar-light" style="background-color: #90EE90;">
      <div class="container">
          <a class="navbar-brand" href="/">Vegan Style</a>
          <div class="collapse navbar-collapse" id="navbarNavDropdown">
            <ul class="navbar-nav">
              <li class="nav-item">
                <a class="nav-link" href="{% url 'track_hash_page' %}">Track Lot In the Blockchain</a>
              </li>
            </ul>
            <ul class="navbar-nav ms-auto">
              {% if request.user.is_staff %}
              <form class="d-flex mx-2" method="POST" action="{% url 'search_tracking_code' %}">
                {% csrf_token %}
                <input name="searched" class="form-control me-2" type="search" placeholder="Search for Tracking code" aria-label="Search">
                <button class="btn btn-outline-success" type="submit">Search</button>
              </form>
              <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                  {{ request.user.username }}
                </a>
                <ul class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink"> 
                  <li><a class="dropdown-item" href="{% url 'lot_registration' %}">Register a new lot</a></li>
                  <li><a class="dropdown-item" href="{% url 'user_profile' pk=request.user.id %}">Profile</a></li>  
                  <li><a class="dropdown-item" href="{% url 'user_list' %}">User List</a></li>               
                  <li><a class="dropdown-item" href="{% url 'password_change' %}">Change Password</a></li>
                  <li><a class="dropdown-item" href="{% url 'logout' %}">Logout</a></li>
                </ul>
              </li>
              {% elif not request.user.is_staff and request.user.is_authenticated %}
                <form class="d-flex mx-2" method="POST" action="{% url 'search_tracking_code' %}">
                  {% csrf_token %}
                  <input name="searched" class="form-control me-2" type="search" placeholder="Search for Tracking code" aria-label="Search">
                  <button class="btn btn-outline-success" type="submit">Search</button>
                </form>
                <li class="nav-item dropdown">
                  <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                    {{ request.user.username }}
                  </a>
                  <ul class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">              
                    <li><a class="dropdown-item" href="{% url 'password_change' %}">Change Password</a></li>
                    <li><a class="dropdown-item" href="{% url 'logout' %}">Logout</a></li>
                  </ul>
                </li>
              {% endif %}
              {% if not request.user.is_authenticated %}
              <li class="nav-item mx-1">
                <a class="nav-link" href="{% url 'registration' %}">Sign Up</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'login' %}">Are you our costumer? Log in!</a>
              </li>
              {% endif %}
            </ul>
          </div>
      </div>  
    </nav>
    {% block content %}
  

    {% endblock content %}
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>

  </body>
</html>